### ISSUE TITLE
g++ not found 

### ISSUE THREAD

**Issue by palivoda** [platformio/platform-native#1]
For Native Environment - run command outputs:
> platformio run
> Verbose mode can be enabled via `-v, --verbose` option
> PLATFORM: Native >
> SYSTEM:
> Library Dependency Finder -> http://bit.ly/configure-pio-ldf
> LDF MODES: FINDER(chain) COMPATIBILITY(light)
> Collected 0 compatible libraries
> Scanning dependencies...
> 
> No dependencies
> Compiling .pioenvs\native\src\main.o
> 'g++' is not recognized as an internal or external command,
> operable program or batch file.
> *** [.pioenvs\native\src\main.o] Error 1

It's Windows 7. PlatformIO 3.5.3a7.  
In PowerShell console in Atom it also says the same.

While in command prompt g++ is found. Its in path. 

Platformio reinstall  does not help.

Can you give me a clue where to dig? :)

**Comment by azeemshatp** [comment]
How did you fix this issue? I have the same problem in Windows 10, platformio powershell. I can access g++ from the command line and not from the PIO powershell.

**Comment by palivoda** [comment]
Unfortunetely I did not found. Maybe you are lucky.

**Comment by ivankravets** [comment]
Please add `bin` folder of your local toolchain to system PATH environment variable in OS. For example, `C:\\MinGW\\bin`

**Comment by mayurpawar2871** [comment]
Processing in native environment as i don't hardware
[.pio/build/native/test/test.o] Error 1
please guide

**Comment by ivankravets** [comment]
Could you share a simple project to reproduce this issue?

**Comment by felixplum** [comment]
Hi, I faced a similar issue and found a simple workaround:


Take a look at

`C:\Users\$USERNAME\.platformio\platforms\native\builder\main.py`

and add the two lines

```python
import os 
os.environ["PATH"] += ";" + r"C:\Program Files\mingw64\bin"
```
or wherever your mingw64 is located. A clean solution would allow appending $PATH or buildchain-configs via the _platformio.ini_. 

Once that is set up, create a sample test file `test/test_main.cpp` with content

```c++
#include <unity.h>

void test_setup(void)
{
    TEST_ASSERT(true);
}

int main(int argc, char **argv)
{
    UNITY_BEGIN();

    RUN_TEST(test_setup);

    UNITY_END();

    return 0;
}
```

Happy testing!

**Comment by ivankravets** [comment]
Hi, @felixplum ,

The proper solution is to add C:\Program Files\mingw64\bin to your system environment PATH variable..

**Comment by felixplum** [comment]
Hey Ivan,

That directory is in the PATH and gcc can be executed outside of the PlatformIO-environment, similarly to OP.
See also: https://community.platformio.org/t/g-is-not-recognized/11256/5

I'm using the official IDE with core 5.2.5 under Windows 10.

**Comment by ivankravets** [comment]
Please disable VSCode suspicious/broken extensions that break the global system environment.
